const envVariables = Object.freeze({
  PORT: "PORT",
  JWT_SECRET: "JWT_SECRET",
  MAIL_HOST: "MAIL_HOST",
  MAIL_USER: "MAIL_USER",
  MAIL_PASSWORD: "MAIL_PASSWORD",
  MAIL_PORT: "MAIL_PORT",
  MAIL_SECURE: "MAIL_SECURE",
  POSTGRES_DB: {
    DB_DIALECT: "DB_DIALECT",
    DB_USERNAME: "DB_USERNAME",
    DB_PASSWORD: "DB_PASSWORD",
    DB_DATABASE: "DB_DATABASE",
    DB_HOST: "DB_HOST",
    DB_PORT: "DB_PORT",
  },
});

export default envVariables;
